
POST https://localhost:7279/login
content-type: application/json

{
  "email": "shashia@gmail.com",
  "password": "123456"
}

###
GET https://localhost:7279/employee/get/69

###

GET https://localhost:8080/employee/get_all

###

PATCH  https://localhost:7279/employee/update/2328
content-type: application/json

{
    "ID": 72,
    "Name": "Maria",
    "LastName": "Varela",
    "BirthDate": "01/01/1980",
    "Age": 19,
    "Position": "Bottom",
    "StartingDate": "01/01/2020"
}
###

POST https://localhost:7279/employee/add
content-type: application/json

{
    "newEmployee": {
        "ID": 20,
        "Name": "Sasha",
        "LastName": "Varela",
        "Email": "shashia@gmail.com",
        "BirthDate": "01/01/1980",
        "Age": 19,
        "Position": "Bottom",
        "StartingDate": "01/01/2020"
        },
    "password": "123456"
}


###

DELETE https://localhost:7279/employee/delete/1000

### ------------Client---------------

GET https://localhost:7279/client/get_all

###
GET https://localhost:7279/client/get/70
###
POST https://localhost:8080/client/add
content-type: application/json

{
    "newClient":{
        "ID": 83,
        "Name": "Sasha",
        "LastName": "Varela",
        "Password": "1234ABC",
        "Email": "ybrenesr@gmail.com",
        "PhoneNumber": 89898989,
        "Address": "Para arriba"
        },
    "password": "123456"
}
###
PATCH  https://localhost:7279/client/update/83
content-type: application/json

{
    "ID": 90,
    "Name": "Sasha",
    "LastName": "Varela",
    "Password": "1234ABC",
    "Email": "ybrenesr@gmail.com",
    "PhoneNumber": 89898989,
    "Address": "Para arriba"
}

###
DELETE https://localhost:7279/client/delete/90
###

PATCH  https://localhost:7279/client/change_password/ybrenesr@gmail.com
content-type: application/json

{
    "oldPassword": "1234ABC",
    "newPassword": "5646",
    "confirmPassword": "5646"
}

### -----------Appointments-----------------

GET https://localhost:7279/appointment/get_all

###

GET https://localhost:7279/appointment/get/69

###

POST https://localhost:7279/appointment/add
content-type: application/json

{
    "ID": 7,
    "Date": "01/01/2020",
    "Time": "01:00",
    "AttendedClientID": 83,
    "SelectedBranch": 32,
    "LicensePlate": "ABC123",
    "SelectedBranch": 69,
    "RequiredService": "Lavado",
    "MechanicID": 69,
    "AssistantID": 69
}

###

PATCH  https://localhost:7279/appointment/update/7
content-type: application/json

{
    "ID": 15,
    "Date": "01/01/2020",
    "Time": "01:00",
    "AttendedClientID": 69,
    "SelectedBranch": 32,
    "LicensePlate": "ABC123",
    "SelectedBranch": 69,
    "RequiredService": "Lavado",
    "MechanicID": 69,
    "AssistantID": 69
}

###
DELETE  https://localhost:7279/appointment/delete/15

###
GET https://localhost:3456/appointment/generate_bill/2

